projects:
  ticket management sytem:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: 57ne733sdzdd5ngrtijwlo3e2u
        maxDepth: 2
extensions:
  amplify:
    version: 3
